<?php

use App\Models\Settings\Branch;
use App\Models\Settings\Salutation;
use App\Models\Customers\Individual;

/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(Individual::class, function ($faker) {
    $faker = Faker\Factory::create('en_UG');
    $branch = Branch::inRandomOrder()->first();

    return [
            'sacco_id'          => $branch->sacco_id,
            'branch_id'         => $branch->id,
            'title'             => $faker->randomElement(array_merge([''], Salutation::DEFAULT_SALUTATIONS)),
            'first_name'        => $faker->firstName,
            'middle_name'       => $faker->randomElement([$faker->lastName, null]),
            'last_name'         => $faker->lastName,
            'dob'               => $faker->dateTimeBetween('1970-01-01', '2007-12-31')->format(MYSQL_DATE_FORMAT),
            'gender'            => $faker->randomElement(['Male', 'Female',]),
            'phone_number'      => $faker->e164PhoneNumber,
            'email'             => $faker->unique()->safeEmail,
            'legacy_address'    => $faker->address,
            'street_address'    => $faker->streetName,
            'city'              => $faker->city,
            'district'          => $faker->state,
            'country'           => $faker->randomElement(['Uganda', 'Zambia', 'Kenya', 'Tanzania', 'Canada']),
            'postcode'          => $faker->postcode,
            'kin_full_name'     => $faker->name,
            'kin_phone_number'  => $faker->e164PhoneNumber,
            'is_subscribed_sms' => $faker->boolean(50),
            'legacy_member_num' => $branch->legacy_branch_prefix .'-'.random_int(1, 80000),
            'has_paid'          => $faker->boolean(50),
            'registration_date' => $faker->dateTimeBetween(SEEDING_SACCO_START, 'now'),

            'photo_path'                 => $faker->randomElement([
                '/img/faker-headshots/model-001.jpg',
                '/img/faker-headshots/model-002.jpg',
                '/img/faker-headshots/model-003.jpg',
                '/img/faker-headshots/model-004.jpg',
                '/img/faker-headshots/model-005.jpg',
                '/img/faker-headshots/model-006.jpg',
                '/img/faker-headshots/model-007.jpg',
                '/img/faker-headshots/model-008.jpg',
                '/img/faker-headshots/model-009.jpg',
                '/img/faker-headshots/model-010.jpg',
                '/img/faker-headshots/model-011.jpg',
                '/img/faker-headshots/model-012.jpg',
                '/img/faker-headshots/model-013.jpg',
                '/img/faker-headshots/model-014.jpg',
                '/img/faker-headshots/model-015.jpg',
                '/img/faker-headshots/model-016.jpg',
                '/img/faker-headshots/model-017.jpg',
                '/img/faker-headshots/model-018.jpg',
                '/img/faker-headshots/model-019.jpg',
                '/img/faker-headshots/model-020.jpg',
                '/img/faker-headshots/model-021.jpg',
                '/img/faker-headshots/model-022.jpg',
                '/img/faker-headshots/model-023.jpg',
                '/img/faker-headshots/model-024.jpg',
                '/img/faker-headshots/model-025.jpg',
                '/img/faker-headshots/model-026.jpg',
                '/img/faker-headshots/model-027.jpg',
                '/img/faker-headshots/model-028.jpg',
                '/img/faker-headshots/model-029.jpg',
                '/img/faker-headshots/model-030.jpg',
                '/img/faker-headshots/model-031.jpg',
                '/img/faker-headshots/model-032.jpg',
                '/img/faker-headshots/model-033.jpg',
                '/img/faker-headshots/model-034.jpg',
                '/img/faker-headshots/model-035.jpg',
                '/img/faker-headshots/model-036.jpg',
                '/img/faker-headshots/model-037.jpg',
                '/img/faker-headshots/model-038.jpg',
                '/img/faker-headshots/model-039.jpg',
                '/img/faker-headshots/model-040.jpg',
                '/img/faker-headshots/model-041.jpg',
                '/img/faker-headshots/model-042.jpg',
                '/img/faker-headshots/model-043.jpg',
                '/img/faker-headshots/model-044.jpg',
                '/img/faker-headshots/model-045.jpg',
                '/img/faker-headshots/model-046.jpg',
                '/img/faker-headshots/model-047.jpg',
                '/img/faker-headshots/model-048.jpg',
                '/img/faker-headshots/model-049.jpg',
                '/img/faker-headshots/model-050.jpg',
                '/img/faker-headshots/model-opio.png',
                '/img/faker-headshots/model-gerald.png',
                '/img/faker-headshots/model-alfred.png',
                '/img/faker-headshots/model-fredrick.png',
                '',
                '',
            ]),
            'signature_path'             => $faker->randomElement([
                '/img/faker-signatures/sig1.png',
                '/img/faker-signatures/sig2.png',
                '/img/faker-signatures/sig3.png',
                '/img/faker-signatures/sig4.png',
                '',
                '',
                '',
                '',
            ]),
            'identification_path'        => $faker->randomElement([
                '/img/faker-ids/id1.jpg',
                '/img/faker-ids/id2.jpg',
                '/img/faker-ids/id3.jpg',
                '/img/faker-ids/id4.jpeg',
                '/img/faker-ids/id5.jpg',
                '/img/faker-ids/id6.png',
                '',
                '',
                '',
                '',
                '',
                '',
            ]),
            'pin'                        => bcrypt($faker->numberBetween(0, 9999)),
            'mobile_money_num'           => $faker->e164PhoneNumber,
            'is_subscribed_mobile_money' => $faker->boolean(50),
            // 'non_individual' => $faker->boolean(50),
        ];
});
